from typing import Any, Protocol


class Store(Protocol):
    """存储抽象接口。当前由 LocalStore 实现，后续可替换为 SqliteStore。"""

    def get_last_rank(self) -> int: ...

    def set_last_rank(self, rank: int) -> None: ...

    def get_word_memory(self) -> dict[str, dict]: ...

    def save_word_memory(self, words: dict[str, dict]) -> None: ...

    def get_word_events(self) -> list[dict]: ...

    def append_word_events(self, events: list[dict]) -> None: ...

    def get_sessions(self) -> dict[str, dict]: ...

    def get_session(self, session_id: str) -> dict: ...

    def save_session(self, session: dict) -> None: ...

    def update_session(self, session_id: str, updates: dict[str, Any]) -> None: ...
